add config parsing

diff --git a/usr/share/anon-ws-disable-stacked-tor/systemd-unit-files-generator b/usr/share/anon-ws-disable-stacked-tor/systemd-unit-files-generator
--- a/usr/share/anon-ws-disable-stacked-tor/systemd-unit-files-generator
+++ b/usr/share/anon-ws-disable-stacked-tor/systemd-unit-files-generator
@@ -13,33 +13,19 @@ cd ..
 cd ..
 cd ..
 
-## Redirect Whonix-Workstation port 9050 to Whonix-Gateway port 9050 and so forth.
-file_port_tuples+=" port#9050:9050 " ## system Tor default SocksPort
-file_port_tuples+=" port#9150:9151 " ## Tor Browser Bundle default SocksPort
-file_port_tuples+=" port#9152:9152 " ## Tor Messenger default SocksPort
-file_port_tuples+=" port#9051:9051 " ## Tor default ControlPort
-file_port_tuples+=" port#9151:9051 " ## Tor Browser Bundle default ControlPort
-file_port_tuples+=" port#9153:9051 " ## Tor Messenger default ControlPort
-file_port_tuples+=" port#11109:9119 " ## TorChat default SocksPort
-
-## Create a unix domain socket files such as
-## /var/run/anon-ws-disable-stacked-tor/127.0.0.1_9050.sock and forward those
-## to $GATEWAY_IP:9150 etc. See also:
-## https://phabricator.whonix.org/T192
-file_port_tuples+=" /var/run/anon-ws-disable-stacked-tor/127.0.0.1_9050.sock#9050 "
-file_port_tuples+=" /var/run/anon-ws-disable-stacked-tor/127.0.0.1_9150.sock#9150 "
-file_port_tuples+=" /var/run/anon-ws-disable-stacked-tor/127.0.0.1_9152.sock#9152 "
-file_port_tuples+=" /var/run/anon-ws-disable-stacked-tor/127.0.0.1_9051.sock#9051 "
-file_port_tuples+=" /var/run/anon-ws-disable-stacked-tor/127.0.0.1_9151.sock#9051 "
-file_port_tuples+=" /var/run/anon-ws-disable-stacked-tor/127.0.0.1_9153.sock#9051 "
-
-## system Tor default SocksSocket is /var/run/tor/socks
-## redirect Whonix-Workstation unix domain socket file /var/run/tor/socks to Whonix-Gateway port 9050
-file_port_tuples+=" /var/run/tor/socks#9050 "
-
-## Debian /usr/share/tor/tor-service-defaults-torrc uses '/var/run/tor/control' Tor ControlSocket
-## Redirect Whonix-Workstation unix domain socket file /var/run/tor/control to Whonix-Gateway port 9051
-file_port_tuples+=" /var/run/tor/control#9051 "
+shopt -s nullglob
+for i in etc/anon-ws-disable-stacked-tor.d/*.conf rw/anon-ws-disable-stacked-tor.d/*.conf; do
+   bash_n_exit_code="0"
+   bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
+   if [ ! "$bash_n_exit_code" = "0" ]; then
+      echo "Invalid config file: $i
+bash_n_exit_code: $bash_n_exit_code
+bash_n_output:
+$bash_n_output" >&2
+      exit 1
+   fi
+   source "$i"
+done
 
 mkdir -p usr/share/lintian/overrides
 
@@ -103,7 +89,7 @@ WantedBy=sockets.target" > "./lib/systemd/system/anon-ws-disable-stacked-tor_aut
 ## Copyright (C) 2018 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
 ## See the file COPYING for copying conditions.
 
-## This file was auto generated by $BASH_SOURCE.
+## This file get auto generated by $BASH_SOURCE.
 
 [Unit]
 Description=redirect $listen_where to Whonix-Gateway port ${destination_port}
